"""
Unit tests for template engine
"""

import pytest
import tempfile
from pathlib import Path
import sys
sys.path.append('.')

from core.template_engine import TemplateEngine
from core.manifest_parser import ManifestParser

class TestTemplateEngine:
    """Test cases for TemplateEngine class"""

    def test_basic_string_rendering(self):
        """Test basic string template rendering"""
        engine = TemplateEngine()

        template_str = "Hello {{ name }}! Your age is {{ age }}."
        context = {'name': 'Robot', 'age': 5}

        result = engine.render_string(template_str, context)
        assert result == "Hello Robot! Your age is 5."

    def test_custom_filters(self):
        """Test custom filters work correctly"""
        engine = TemplateEngine()

        template_str = """
Name: {{ name }}
Snake: {{ name | snake_case }}
Camel: {{ name | camel_case }}
Safe: {{ name | safe_identifier }}
"""
        context = {'name': 'My Robot Name'}

        result = engine.render_string(template_str, context)
        assert 'my_robot_name' in result  # snake_case
        assert 'MyRobotName' in result    # camel_case

    def test_custom_functions(self):
        """Test custom global functions"""
        engine = TemplateEngine()

        template_str = """
Generated: {{ timestamp() }}
Date: {{ iso_date() }}
Range check: {{ range_check(5, 1, 10) }}
"""
        context = {}

        result = engine.render_string(template_str, context)
        assert 'Generated:' in result
        assert 'Date:' in result
        assert 'True' in result  # range_check result

    def test_file_header_function(self):
        """Test file header generation"""
        engine = TemplateEngine()

        template_str = "{{ file_header('test.py', 'Test file') }}"
        context = {}

        result = engine.render_string(template_str, context)
        assert '#!/usr/bin/env python3' in result
        assert 'test.py' in result
        assert 'Test file' in result
        assert 'Generated by ZettaWare' in result

    def test_manifest_context_creation(self):
        """Test creating context from robot manifest"""
        # Load the Transbot manifest
        manifest_path = Path('robots/yahboom_transbot/robot.yaml')
        parser = ManifestParser(manifest_path)
        manifest = parser.parse()

        engine = TemplateEngine()
        context = engine.create_context_from_manifest(manifest)

        # Check basic fields
        assert context['robot_name'] == 'Yahboom Transbot'
        assert context['robot_type'] == 'differential_drive'
        assert context['robot_platform'] == 'jetson_nano'

        # Check derived fields
        assert context['robot_name_safe'] == 'Yahboom_Transbot'
        assert context['robot_name_snake'] == 'yahboom_transbot'
        assert context['robot_name_camel'] == 'YahboomTransbot'

        # Check boolean flags
        assert context['has_motors'] == True
        assert context['has_sensors'] == True
        assert context['has_camera'] == True
        assert context['has_imu'] == True
        assert context['has_ultrasonic'] == True
        assert context['has_arm'] == True

    def test_list_templates(self):
        """Test template listing functionality"""
        engine = TemplateEngine()
        templates = engine.list_templates()

        # Should find our test template
        assert any('test/hello_robot.py.template' in t for t in templates)

    def test_template_validation(self):
        """Test template validation"""
        engine = TemplateEngine()

        # Test valid template
        result = engine.validate_template('test/hello_robot.py.template')
        assert result['valid'] == True
        assert len(result['errors']) == 0

if __name__ == "__main__":
    # Simple test runner for development
    test = TestTemplateEngine()

    print("Running template engine tests...")

    tests = [
        ('basic_string_rendering', test.test_basic_string_rendering),
        ('custom_filters', test.test_custom_filters),
        ('custom_functions', test.test_custom_functions),
        ('file_header_function', test.test_file_header_function),
        ('manifest_context_creation', test.test_manifest_context_creation),
        ('list_templates', test.test_list_templates),
        ('template_validation', test.test_template_validation),
    ]

    passed = 0
    failed = 0

    for test_name, test_func in tests:
        try:
            test_func()
            print(f"[OK] {test_name}")
            passed += 1
        except Exception as e:
            print(f"[FAIL] {test_name}: {e}")
            failed += 1

    print(f"\nResults: {passed} passed, {failed} failed")