"""
Template Engine for ZettaWare
Processes Jinja2 templates with robot manifest data
"""

import os
import re
from pathlib import Path
from typing import Dict, Any, Optional, List
from jinja2 import Environment, FileSystemLoader, Template, TemplateError
from jinja2.filters import do_upper, do_lower
from datetime import datetime

class TemplateEngine:
    """
    Template processor for generating robot development suites.
    Uses Jinja2 with custom filters and functions for robot code generation.
    """

    def __init__(self, template_dirs: Optional[List[Path]] = None):
        """
        Initialize template engine with search directories.

        Args:
            template_dirs: List of directories to search for templates
        """
        if template_dirs is None:
            # Default to templates directory relative to this file
            base_dir = Path(__file__).parent.parent
            template_dirs = [base_dir / "templates"]

        # Convert to strings for Jinja2
        self.template_dirs = [str(d) for d in template_dirs]

        # Set up Jinja2 environment
        self.env = Environment(
            loader=FileSystemLoader(self.template_dirs),
            trim_blocks=True,
            lstrip_blocks=True,
            keep_trailing_newline=True
        )

        # Add custom filters and functions
        self._setup_custom_filters()
        self._setup_custom_functions()

    def _setup_custom_filters(self):
        """Add custom Jinja2 filters for robot code generation"""

        def snake_case(text):
            """Convert text to snake_case"""
            # First handle spaces and hyphens
            text = str(text).replace(' ', '_').replace('-', '_')
            # Then handle camelCase
            s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', text)
            return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).lower()

        def camel_case(text):
            """Convert text to CamelCase"""
            words = str(text).replace('_', ' ').replace('-', ' ').split()
            return ''.join(word.capitalize() for word in words)

        def pascal_case(text):
            """Convert text to PascalCase (same as CamelCase)"""
            return camel_case(text)

        def kebab_case(text):
            """Convert text to kebab-case"""
            return snake_case(text).replace('_', '-')

        def safe_identifier(text):
            """Convert text to safe Python identifier"""
            # Remove invalid characters and ensure it starts with letter/underscore
            text = re.sub(r'[^a-zA-Z0-9_]', '_', str(text))
            if text and text[0].isdigit():
                text = '_' + text
            return text or '_'

        def format_comment(text, width=70, prefix="# "):
            """Format text as a comment block"""
            lines = []
            words = str(text).split()
            current_line = prefix

            for word in words:
                if len(current_line + word + " ") <= width:
                    current_line += word + " "
                else:
                    lines.append(current_line.rstrip())
                    current_line = prefix + word + " "

            if current_line.strip() != prefix.strip():
                lines.append(current_line.rstrip())

            return '\n'.join(lines)

        def indent_code(text, spaces=4):
            """Indent code block by specified spaces"""
            indent = ' ' * spaces
            return '\n'.join(indent + line if line.strip() else line
                           for line in str(text).split('\n'))

        # Register filters
        self.env.filters['snake_case'] = snake_case
        self.env.filters['camel_case'] = camel_case
        self.env.filters['pascal_case'] = pascal_case
        self.env.filters['kebab_case'] = kebab_case
        self.env.filters['safe_identifier'] = safe_identifier
        self.env.filters['format_comment'] = format_comment
        self.env.filters['indent_code'] = indent_code

    def _setup_custom_functions(self):
        """Add custom Jinja2 global functions"""

        def timestamp():
            """Generate current timestamp"""
            return datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        def iso_date():
            """Generate current date in ISO format"""
            return datetime.now().strftime("%Y-%m-%d")

        def file_header(filename, description="Generated file", author="ZettaWare"):
            """Generate standard file header"""
            return f"""#!/usr/bin/env python3
# -*- coding: utf-8 -*-
\"\"\"
{filename}
{description}

Generated by ZettaWare on {timestamp()}
Author: {author}

DO NOT EDIT DIRECTLY - This file is auto-generated from templates
\"\"\"
"""

        def range_check(value, min_val, max_val):
            """Check if value is within range"""
            return min_val <= value <= max_val

        def list_to_dict(items, key_field):
            """Convert list of objects to dictionary keyed by field"""
            result = {}
            for item in items:
                if hasattr(item, key_field):
                    result[getattr(item, key_field)] = item
                elif isinstance(item, dict) and key_field in item:
                    result[item[key_field]] = item
            return result

        # Register global functions
        self.env.globals['timestamp'] = timestamp
        self.env.globals['iso_date'] = iso_date
        self.env.globals['file_header'] = file_header
        self.env.globals['range_check'] = range_check
        self.env.globals['list_to_dict'] = list_to_dict

    def render_template(self, template_path: str, context: Dict[str, Any]) -> str:
        """
        Render a template file with the given context.

        Args:
            template_path: Path to template file relative to template directories
            context: Dictionary of variables to pass to template

        Returns:
            Rendered template content

        Raises:
            TemplateError: If template cannot be found or rendered
        """
        try:
            template = self.env.get_template(template_path)
            return template.render(**context)
        except TemplateError as e:
            raise TemplateError(f"Template rendering failed for '{template_path}': {e}")
        except Exception as e:
            raise TemplateError(f"Unexpected error rendering '{template_path}': {e}")

    def render_string(self, template_str: str, context: Dict[str, Any]) -> str:
        """
        Render a template string with the given context.

        Args:
            template_str: Template content as string
            context: Dictionary of variables to pass to template

        Returns:
            Rendered template content
        """
        try:
            template = self.env.from_string(template_str)
            return template.render(**context)
        except TemplateError as e:
            raise TemplateError(f"String template rendering failed: {e}")
        except Exception as e:
            raise TemplateError(f"Unexpected error rendering string template: {e}")

    def list_templates(self, pattern: str = "*.template") -> List[str]:
        """
        List available templates matching pattern.

        Args:
            pattern: Glob pattern to match template files

        Returns:
            List of template paths
        """
        templates = []
        for template_dir in self.template_dirs:
            template_path = Path(template_dir)
            if template_path.exists():
                for template_file in template_path.rglob(pattern):
                    # Get relative path from template directory
                    rel_path = template_file.relative_to(template_path)
                    templates.append(str(rel_path))

        return sorted(list(set(templates)))  # Remove duplicates and sort

    def validate_template(self, template_path: str) -> Dict[str, Any]:
        """
        Validate a template for syntax errors.

        Args:
            template_path: Path to template file

        Returns:
            Dictionary with validation results
        """
        result = {
            'valid': False,
            'errors': [],
            'warnings': [],
            'variables': []
        }

        try:
            template = self.env.get_template(template_path)

            # Try to get template variables (this is approximate)
            # Jinja2 doesn't provide direct access to template variables
            ast = self.env.parse(template.source)
            variables = set()

            # Walk the AST to find variable references
            for node in ast.find_all():
                if hasattr(node, 'name'):
                    variables.add(node.name)

            result['variables'] = sorted(list(variables))
            result['valid'] = True

        except TemplateError as e:
            result['errors'].append(str(e))
        except Exception as e:
            result['errors'].append(f"Unexpected error: {e}")

        return result

    def create_context_from_manifest(self, manifest) -> Dict[str, Any]:
        """
        Create template context from robot manifest.

        Args:
            manifest: RobotManifest object

        Returns:
            Dictionary suitable for template rendering
        """
        context = {
            # Robot metadata
            'robot_name': manifest.name,
            'robot_type': manifest.type,
            'robot_platform': manifest.platform,
            'robot_name_safe': self.env.filters['safe_identifier'](manifest.name),
            'robot_name_snake': self.env.filters['snake_case'](manifest.name),
            'robot_name_camel': self.env.filters['camel_case'](manifest.name),

            # Hardware
            'motors': manifest.motors,
            'sensors': manifest.sensors,
            'actuators': manifest.actuators,
            'power': manifest.power,

            # Configuration
            'capabilities': manifest.capabilities,
            'libraries': manifest.libraries,

            # Derived values
            'has_motors': manifest.motors is not None,
            'has_sensors': len(manifest.sensors) > 0,
            'has_actuators': len(manifest.actuators) > 0,
            'has_camera': 'camera' in manifest.sensors,
            'has_imu': 'imu' in manifest.sensors,
            'has_ultrasonic': 'ultrasonic' in manifest.sensors,
            'has_arm': 'arm' in manifest.actuators,
            'has_leds': any('led' in name.lower() for name in manifest.actuators.keys()),

            # Raw manifest for custom access
            'manifest': manifest,
            'raw_data': manifest.raw_data,

            # Generation metadata
            'generation_timestamp': datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            'zettaware_version': "1.0.0"
        }

        return context